branches:
  only:
  - master
  - develop
language: android
before_install:
  - openssl aes-256-cbc -K $encrypted_9916a39c4a12_key -iv $encrypted_9916a39c4a12_iv
    -in test-release.keystore.enc -out ./android/app/test-release.keystore -d
  - nvm install 12
  - node --version
  - npm -g install typescript
install:
- yarn
android:
  components:
  - build-tools-28.0.3
  - android-28
  - build-tools-29.0.2
  - android-29
script:
  - yarn lint
  - yarn build-android
after_success:
  - chmod +x ./upload-apk.sh
  - "./upload-apk.sh"
